version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8888:80"
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 80
    env_file:
      - .local_dev.env
    volumes:
      - .:/opt/project

  tests:
    build:
      context: .
    command: bash -c "coverage run -m --source=app pytest -v tests && coverage report -m"
    env_file:
      - .local_dev.test.env
    volumes:
      - .:/opt/project

  unit_tests:
    build:
      context: .
    command: bash -c "coverage run -m --source=app pytest -v tests/unit_tests && coverage report -m"
    env_file:
      - .local_dev.test.env
    volumes:
      - .:/opt/project

  integration_tests:
    build:
      context: .
    command: /bin/sh -c "coverage run -m --source=app pytest -v tests/integration_tests && coverage report -m"
    env_file:
      - .local_dev.test.env
    volumes:
      - .:/opt/project

  upgrade:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
    command: bash -c "pip install -i https://gitlab-runner:AP2bGdYxE44HuBLmpGHwTCxiY1vN5Pcq9ZbG9A@hapimag.jfrog.io/artifactory/api/pypi/pipy-proxy/simple --upgrade -r /opt/project/requirements/requirements.txt && pip freeze > /opt/project/requirements-freezed.txt"
    volumes:
      - .:/opt/project
